import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Nav from '@/components/Nav'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Next Movie List',
  description: 'Generated by pz',
}

export default async   function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {  
  return (
    <html lang="en">
      
      <body className={inter.className}>
        <Nav />
        {/* {state === 'loading' ? (
          <div className="w-screen absolute inset-0 h-screen flex flex-col justify-center items-center">
            <p className='text-xl'>Loading...</p>
          </div>
        ) : ( */}
          {children}
        {/* )} */}
        <div className='h-40'>

        </div>
      </body>
    </html>
  )
}
